// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1:string):Promise<Record<string, any>>;

export function CodeAssist(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CompleteLesson(arg1:number):Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetLessonDetail(arg1:number):Promise<Record<string, any>>;

export function GetLessons():Promise<Array<Record<string, any>>>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
