// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function CodeAssist(arg1, arg2) {
  return window['go']['main']['App']['CodeAssist'](arg1, arg2);
}

export function CompleteLesson(arg1) {
  return window['go']['main']['App']['CompleteLesson'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetLessonDetail(arg1) {
  return window['go']['main']['App']['GetLessonDetail'](arg1);
}

export function GetLessons() {
  return window['go']['main']['App']['GetLessons']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}
